config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }
  root 'tests#index'

  resources :users, only: :create
  resources :sessions, only: :create

  resources :tests do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: :index
  get '/badges/my', to: 'badges#my'

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  extend Enumerize

  enumerize :rule, in: %i[category_badge single_badge level_badge]

  before_save do
    self.cover = '../../kubok.png' if cover.blank?
  end

  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  scope :for_category, -> { where(rule: 'category_badge') }
  scope :for_single, -> { where(rule: 'single_badge') }
  scope :for_level, -> { where(rule: 'level_badge') }

  validates :title, presence: true
  validates :rule, presence: true
  validate :validate_badges_by_category

  def find_tests
    case rule
    when 'category_badge'
      category = Category.find_by(title: primary_param)
      Test.all.where(category_id: category)
    when 'single_badge'
      Test.all.where(title: primary_param, level: secondary_param)
    when 'level_badge'
      Test.all.where(level: primary_param)
    end
  end

  private

  def validate_badges_by_category
    case rule
    when 'category_badge'
      errors.add(:primary_param) unless Category.exists?(title: primary_param)
    when 'single_badge'
      errors.add(:secondary_param) unless Test.exists?(title: primary_param, level: secondary_param)
    when 'level_badge'
      errors.add(:primary_param) unless Test.exists?(level: primary_param)
    end
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to admin_badge_path(@badge)
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path(@badge)
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path, notice: I18n.t('.destroy', title: @badge.title)
  end

  private

  def badge_params
    params[:badge].permit(:title, :rule, :cover, :primary_param, :secondary_param)
  end

  def find_badge
    @badge = Badge.find(params[:id])
  end
end

app/controllers/badges_controller.rb
class BadgesController < AuthController
  def index
    @badges = Badge.all
  end

  def my
    @badges = current_user.badges
  end
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td><%= badge.title %></td>
  <td><%= badge.rule %></td>
  <td><%= badge.primary_param %></td>
  <td><%= badge.secondary_param.presence %></td>
  <td>
    <%= link_to (octicon 'eye', class: 'text-secondary'), admin_badge_path(badge)%>
    <%= link_to (octicon 'pencil', class: 'text-secondary'), edit_admin_badge_path(badge) %>
    <%= link_to (octicon 'trashcan', class: 'text-danger'),
                    admin_badge_path(badge),
                    method: :delete,
                    data: { confirm: 'Are you sure?'} %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<%= render 'shared/errors', resource: @badge %>

<%= form_with(model: [:admin, @badge], local: true) do |f| %>
    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :cover %><br>
      <%= f.text_field :cover, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :rule %><br>
      <%= f.select :rule,
                   Badge.rule.options,
                   { include_blank: I18n.t('.select_category') },
                   id: 'category_input',
                   class: 'form-control'%>
    </div>

    <div class="form-group" style="padding: 15px;">
      <div id="primary_param" class="hide">
        <%= f.label :primary_param %><br>
        <%= f.text_field :primary_param, class: 'form-control' %>
      </div>
      
      <p id="secondary_param" class="hide">
        <%= f.label :secondary_param %><br>
        <%= f.text_field :secondary_param, class: 'form-control' %>
      </p>
    </div>

    <%= f.submit t('.save'),class: 'btn btn-success mt-2' %>
<% end%>

app/views/admin/badges/edit.html.erb
<h1><%= t('.edit_badge')%></h1>

<%= render 'form' %>

app/views/admin/badges/index.html.erb
<h1><%= t('.all_badge')%></h1>

<%= link_to t('.new_badge'), new_admin_badge_path, class: 'btn btn-success' %>

<table class="table">
  <tr>
    <td><%= t('.title')%></td>
    <td><%= t('.cover')%></td>
    <td colspan="2"><%= t('.params')%></td>
    <td><%= t('.actions')%></td>
  </tr>
  <tbody>
    <%= render @badges %>
  </tbody>
</table>

<%= link_to t('.back'), admin_tests_path %>

app/views/admin/badges/new.html.erb
<h1><%= t('.create_badge')%></h1>

<%= render 'form' %>

app/views/admin/badges/show.html.erb
<div class="card">
  <img class="card-img-top badge-img" src="<%= @badge.cover %>" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><%= @badge.title %></h5>
    <p class="card-text">
      Выдается <%= @badge.rule %> <%=@badge.primary_param %>
      <%= @badge.secondary_param if @badge.rule == 'single_badge' %>
    </p>
    <div class="badge-buttons">
      <%= link_to t('.update'), edit_admin_badge_path(@badge) %>
      <%= link_to t('.delete'),
                  admin_badge_path(@badge),
                  method: :delete,
                  data: { confirm: 'Are you sure?'} %>
    </div>
  </div>
</div>

<%= link_to t('.back'), admin_badges_path %>