config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }
  root 'tests#index'

  resources :users, only: :create
  resources :sessions, only: :create

  resources :tests do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: :index
  get '/badges/my', to: 'badges#my'

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  extend Enumerize

  enumerize :rule, in: %i[category_badge single_badge level_badge]

  before_save do
    self.cover = '../../kubok.png' if cover.blank?
  end

  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  scope :for_category, -> { where(rule: 'category_badge') }
  scope :for_single, -> { where(rule: 'single_badge') }
  scope :for_level, -> { where(rule: 'level_badge') }

  validates :title, presence: true
  validates :rule, presence: true
  validate :validate_badges_by_category

  def find_tests
    case rule
    when 'category_badge'
      category = Category.find_by(title: primary_param)
      Test.all.where(category_id: category)
    when 'single_badge'
      Test.all.where(title: primary_param, level: secondary_param)
    when 'level_badge'
      Test.all.where(level: primary_param)
    end
  end

  private

  def validate_badges_by_category
    case rule
    when 'category_badge'
      errors.add(:primary_param) unless Category.exists?(title: primary_param)
    when 'single_badge'
      errors.add(:secondary_param) unless Test.exists?(title: primary_param, level: secondary_param)
    when 'level_badge'
      errors.add(:primary_param) unless Test.exists?(level: primary_param)
    end
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to admin_badge_path(@badge)
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path(@badge)
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path, notice: I18n.t('.destroy', title: @badge.title)
  end

  private

  def badge_params
    params[:badge].permit(:title, :rule, :cover, :primary_param, :secondary_param)
  end

  def find_badge
    @badge = Badge.find(params[:id])
  end
end

app/controllers/badges_controller.rb
class BadgesController < AuthController
  def index
    @badges = Badge.all
  end

  def my
    @badges = current_user.badges
  end
end

app/views/badges/_badge.html.erb
<div class="col-3 offset-1 card badge-card">
  <img class="card-img-top badge-img" src="<%= badge.cover %>" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><%= badge.title %></h5>
    <p class="card-text">
      Выдается <%= badge.rule %> <%=badge.primary_param %>
      <% if badge.rule == 'single_badge' %>
        уровня <%= badge.secondary_param %>
      <% end %>
    </p>
  </div>
</div>

app/views/badges/index.html.erb
<h1><%= t('.all_badges') %></h1>
<%= link_to t('.main'), tests_path, class: 'btn btn-primary mb-2' %>
<%= link_to t('.my'), badges_my_path, class: 'btn btn-primary mb-2' %>


<div class="row justify-content-around">
    <%= render @badges %>
</div>

app/views/badges/my.html.erb
<h1><%= t('.my_badges') %></h1>
<%= link_to t('.back'), badges_path, class: 'btn btn-primary mb-2' %>

<div class="row justify-content-around">
    <%= render @badges %>
</div>