config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }
  root 'tests#index'

  resources :users, only: :create
  resources :sessions, only: :create

  resources :tests do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: :index
  get '/badges/my', to: 'badges#my'

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_MINIMAL = 85

  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_question

  before_save :before_save_set_result

  scope :successfull, -> { where('result > :success_minimal', success_minimal: SUCCESS_MINIMAL) }

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def completed?
    current_question.nil?
  end

  def empty_answer?(answer_ids)
    answer_ids.nil?
  end

  def result_to_percent
    correct_questions.to_f / test.questions.count * 100
  end

  def success?
    result_to_percent >= SUCCESS_MINIMAL
  end

  def question_number
    test.questions.where('id < ?', current_question.id).count + 1
  end

  def remaining_time
    (active_until - Time.current).to_i
  end

  def end_time?
    Time.current > active_until
  end

  def stop
    self.current_question = nil
  end

  private

  def before_save_set_result
    self.result = result_to_percent
  end

  def before_validation_set_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    return test.questions.first if current_question.nil?
    test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def active_until
    created_at + test.timer.minutes
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :find_test_passage, only: %i[show result update]
  before_action :check_time, only: :update

  def show; end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      current_user.badges << BadgeService.new(@test_passage).build
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def gist
    @result = GistQuestionService.new.create_gist(@test_passage.current_question)

    if @result.success?
      @gist = Gist.create!(gist_params)
      flash[:notice] = t('.success', link: @result.html_url)
    else
      flash[:alert] = t('.failure')
    end
    redirect_to @test_passage
  end

  private

  def check_time
    @test_passage.stop if check_remaining_time
  end

  def check_remaining_time
    @test_passage.test.with_timer? && @test_passage.end_time?
  end

  def find_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

  def gist_params
    {
      question: @test_passage.current_question,
      gist_url: @result.html_url,
      user: current_user
    }
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def result_style(test_passage)
    test_passage.success? ? 'success' : 'fail'
  end

  def question_count(test_passage)
    "#{test_passage.question_number} of #{test_passage.test.questions.size}"
  end
end

app/views/test_passages/result.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>

<h2 class="<%= result_style(@test_passage) %>" >
  Your result: <%= @test_passage.result %>%
</h2>
<%= link_to t('.button'), tests_path%>

app/views/test_passages/show.html.erb
<h2><%= t('.header', title: @test_passage.test.title) %></h2>
<!-- <p><%= t('.question_count', q_count: question_count(@test_passage)) %><br> -->
<div class="progress-container">
  <%= content_tag :div, '', class: 'progress-bar',
                  data: {
                    current_question: @test_passage.question_number,
                    all_question: @test_passage.test.questions.size
                  } %>
</div>

<% if @test_passage.test.timer > 0 %>
<div class="remaining_time" >
  <%= t('.remaining_time') %>: <%= content_tag :span, '', class: 'timer', data: { time: @test_passage.remaining_time } %>
</div>
<% end %>

<p>
  <b><%= @test_passage.current_question.body %></b>
</p>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids,
                                  @test_passage.current_question.answers,
                                  :id,
                                  :body,
                                  include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label  %>
    </p>
  <% end %>

  <div class="buttons mt-1">
    <%= link_to t('.gist_question'), gist_test_passage_path(@test_passage), method: :post, class: 'btn btn-primary'  %>
    <%= form.submit t('.next'), class: 'btn btn-primary' %>
  </div>
<% end %>

<p class="exit-button"><%= link_to t('.exit'), tests_path, class: 'btn btn-secondary mt-2' %></p>