config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }
  root 'tests#index'

  resources :users, only: :create
  resources :sessions, only: :create

  resources :tests do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: :index
  get '/badges/my', to: 'badges#my'

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_answer_count, on: :create

  private

  def validate_answer_count
    errors.add(:question_id) if question.answers.count > 3
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :find_answer, only: %i[show edit update destroy]
  before_action :find_question, only: %i[new create]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to admin_question_path(@answer.question), notice: 'Answer was successfully created.'
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_question_path(@answer.question), notice: 'Answer was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question), notice: 'Answer was successfully destroyed.'
  end

  private

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end

  def find_question
    @question = Question.find(params[:question_id])
  end
end

app/controllers/answers_controller.rb
class AnswersController < AuthController

  before_action :find_answer, only: %i[show edit update destroy]
  before_action :find_question, only: %i[new create]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to @answer, notice: 'Answer was successfully created.'
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to @answer, notice: 'Answer was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to @answer.question, notice: 'Answer was successfully destroyed.'
  end

  private

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end

  def find_question
    @question = Question.find(params[:question_id])
  end
end

app/views/admin/answers/_answer.html.erb
<li>
  <%= answer.body %><br>
  <%= link_to t('.show'), admin_answer_path(answer) %>
  <%= link_to t('.edit'), edit_admin_answer_path(answer) %>
  <%= link_to t('.delete'),
      admin_answer_path(answer),
      method: :delete,
            data: { confirm: t('.confirm') }
  %><br>
</li>

app/views/admin/answers/_form.html.erb
<%= form_with(model: [:admin, @question, @answer], local: true) do |form| %>
  <%= render 'shared/errors', resource: @answer %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, id: :answer_body, rows: 5, cols: 50 %><br>
  </p>
  <p>
    <%= form.check_box :correct, id: :answer_correct %><br>
    <%= form.label :correct %><br>
  </p>
  <p>
    <%= form.submit %><br>
  </p>
<% end %>

app/views/admin/answers/edit.html.erb
<h1><%= t('.header') %></h1>

<h3><%= @answer.question.body %></h3>


<%= render 'form', answer: @answer %>

<%= link_to t('.show'), admin_answer_path(@answer) %> |
<%= link_to t('.back'), admin_test_path(@answer.question.test) %>

app/views/admin/answers/new.html.erb
<h1><%= t('.header') %></h1>

<h3><%= @question.body %></h3>


<%= render 'form', answer: @answer %>

<%= link_to t('.back'), admin_question_path(@question) %>

app/views/admin/answers/show.html.erb
<h3>
  <%= @answer.question.body%>
</h3>

<p>
  <%= t('.body', body: @answer.body)%>
</p>

<p>
  <%= t('.correct', correct: @answer.correct)%>
</p>

<%= link_to t('.back'), admin_question_path(@answer.question) %>